name: deploy
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'Dockerfile'
    branches: ['master']
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'Dockerfile'
    branches: ['master']

env:
  NODE_VERSION: '20'
  DOCKER_IMAGE: 'akdfkeks/v8ight-be'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 적절한 Node.js 버전으로 설정

      - name: Install dependencies with yarn
        run: yarn install

      - name: Run tests
        run: yarn run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest
            docker stop ${{env.DOCKER_IMAGE}} || true
            docker rm ${{env.DOCKER_IMAGE}} || true
            docker run -d --name ${{env.DOCKER_IMAGE}} -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest
