name: deploy
on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - package.json
      - Dockerfile
    branches: ['master']
  pull_request:
    paths:
      - src/**
      - package.json
      - Dockerfile
    branches: ['master']

env:
  NODE_VERSION: 20
  DOCKER_IMAGE: v8ight-be

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 적절한 Node.js 버전으로 설정

      - name: Install dependencies with yarn
        run: yarn install

      - name: Run tests
        run: yarn run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest

      - name: Create ENV file
        run: |
          touch .env.prod
          ehco MYSQL_HOST=${{secrets.MYSQL_HOST}} >> .env.prod
          ehco MYSQL_PORT=${{secrets.MYSQL_PORT}} >> .env.prod
          ehco MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}} >> .env.prod
          ehco MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}} >> .env.prod
          ehco MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} >> .env.prod
          ehco AWS_S3_REGION=${{secrets.AWS_S3_REGION}} >> .env.prod
          ehco AWS_S3_BUCKET=${{secrets.AWS_S3_BUCKET}} >> .env.prod
          ehco AWS_S3_ACCESS_KEY_ID=${{secrets.AWS_S3_ACCESS_KEY_ID}} >> .env.prod
          ehco AWS_S3_SECRET_ACCESS_KEY=${{secrets.AWS_S3_SECRET_ACCESS_KEY}} >> .env.prod

      - name: Copy ENV to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: .env.prod
          target: /home/ubuntu

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest
            docker stop ${{env.DOCKER_IMAGE}} || true
            docker rm ${{env.DOCKER_IMAGE}} || true
            docker run -d --name ${{env.DOCKER_IMAGE}} -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest
